### ISSUE TITLE
[Question] Use RBQueue without type coercion

### ISSUE THREAD

**Issue by eadf** [dbyr/rb_tree#12]
I've been trying to use the RBQueue inside a plain struct, but I can't get it to compile.
I got this far:
```
trait NewTraitSuggestedByTheCompiler: Copy + Fn(&i32, &i32) -> std::cmp::Ordering {}

struct SimpleTest {
    queue: rb_tree::RBQueue<u32, NewTraitSuggestedByTheCompiler>,
}

impl Default for SimpleTest {
    fn default() -> Self{
        Self {
            queue: rb_tree::RBQueue::new(|l: &i32, r:&i32| {
                l.cmp(r)
            })
        }
    }
}
```
The compiler claims that the word `Copy` I clearly added to `NewTraitSuggestedByTheCompiler`  does not exist.

What am I missing?

The RBQueue  examples I've looked at so far all declares and defines the object in one go and that works, but splitting up 
declaration and definition like one does in a struct seems problematic.

Sure, one could break out the `P` with `SimpleTest<P>` and let type coercion handle it, but that exposes the inner workings of the struct. And we would have to do that all the way up to main().

Maybe a workin example of this can be added to the documentation?

**Comment by dbyr** [comment]
Does something like this work for your use case?
```rust
struct SimpleTest {
    queue: rb_tree::RBQueue<i32, &'static dyn Fn(&i32, &i32) -> std::cmp::Ordering>,
}

impl Default for SimpleTest {
    fn default() -> Self{
        Self {
            queue: rb_tree::RBQueue::new(&|l: &i32, r:&i32| {
                l.cmp(r)
            })
        }
    }
}

fn main() {
    let mut c = SimpleTest::default();
    c.queue.insert(1i32);
}
```
I think the initial issue that may be causing you to get the error you posted about is that you had u32 as the stored type but a comparator type that was trying to accept &i32 instead of &u32. If this is fine I'll add an example to the examples folder.

Also, I've noted that the Copy trait was only used for a single method in the entire RBQueue suite, so I decided to implement that method another way and so I've removed the Copy trait from the functional trait requirements.

**Comment by eadf** [comment]
Thanks, the thing that got me stuck is that I tried to use a closure as argument, just like the Readme.md example.
Using a reference to a closure works so much better.

The u32 was just a typo when I simplified my example. The main problem was 'the trait `Copy` is not implemented for...' 

When you remove the Copy trait, will the 'constructor' in this case accept a plain closure again? That would be great, cause then no further examples will be needed in the examples folder. It would just work as expected.

**Comment by dbyr** [comment]
> When you remove the Copy trait, will the 'constructor' in this case accept a plain closure again? 

I don't think so. I think the issue there is that if there's no generic to deal with it dynamically/case-by-case then the struct cannot be compiled because it doesn't know until instantiation how big the function it needs to contain is. The solution to that is to use a reference to the function (because all references have the same size, so the method can compile without having to know the size of the exact method that will be used is).

**Comment by eadf** [comment]
Maybe a Boxed closure?

**Comment by dbyr** [comment]
That works fine, but I suppose at that point it's just down to personal preference.

**Comment by eadf** [comment]
As long as the Box doesn't have to be part of the signature for it to work, yeah, I guess so.

Edit: Yes, now when `Copy` is gone the more intuitive Boxed version works as well:
```
struct SimpleTest {
    queue: rb_tree::RBQueue<i32, Box<Fn(&i32, &i32) -> std::cmp::Ordering >>,
}

impl Default for SimpleTest {
    fn default() -> Self{
        Self {
            queue: rb_tree::RBQueue::new(Box::new(|l: &i32, r:&i32| {
                l.cmp(r)
            }))
        }
    }
}
```
